"""Add presentation_token to teams

Revision ID: dd87278924a7
Revises: h3c4d5e6f7g8
Create Date: 2026-04-26 12:33:29.005423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd87278924a7'
down_revision = 'h3c4d5e6f7g8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_access', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_organization_access', 'organization_access', ['user_id', 'organization_id'])
    op.drop_column('organization_access', 'granted_at')
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('teams', sa.Column('presentation_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_teams_presentation_token'), 'teams', ['presentation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_presentation_token'), table_name='teams')
    op.drop_column('teams', 'presentation_token')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('organization_access', sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint('uq_organization_access', 'organization_access', type_='unique')
    op.drop_column('organization_access', 'created_at')
    # ### end Alembic commands ###
